### PR TITLE
Compare status messages in a case-insensitive manner

### LINKED ISSUE #13: Job status check is case sensitive
The example configuration does not work for me as my job returns a fully lower-case "success"/"failure"/"cancelled". It appears that the script checks for "Success" with a capital S which causes my job to be reported as status unknown. 

Proposed fix is to just [convert the input string to lower case](https://stackoverflow.com/questions/2264428/how-to-convert-a-string-to-lower-case-in-bash) and check against lower case versions of the current strings.

### PR DESCRIPTION
**Pull request by varGeneric**
Closes #13. 

This fix requires Bash 4.0, I don't think any GitHub actions runners use anything older than that so this should be mergeable without any breakage.

### CODE REVIEW

File: send.sh [hunk 1]
```diff
@@ -12,13 +12,13 @@ echo -e "[Webhook]: Sending webhook to Discord...\\n";
 
 AVATAR="https://github.com/actions.png"
 
-case $1 in
-  "Success" )
+case ${1,,} in
```
Comment (lcombs15) [inline send.sh:16]: Would you add a comment to some form of GNU docs that explains how this works?

Comment (varGeneric) [reply send.sh:16]: From [the Bash manual](https://www.gnu.org/software/bash/manual/bash.html):

> ${parameter^pattern}
> ${parameter^^pattern}
> ${parameter,pattern}
> ${parameter,,pattern}
> This expansion modifies the case of alphabetic characters in parameter. The pattern is expanded to produce a pattern just as in filename expansion. Each character in the expanded value of parameter is tested against pattern, and, if it matches the pattern, its case is converted. The pattern should not attempt to match more than one character. The ‘^’ operator converts lowercase letters matching pattern to uppercase; the ‘,’ operator converts matching uppercase letters to lowercase. The ‘^^’ and ‘,,’ expansions convert each matched character in the expanded value; the ‘^’ and ‘,’ expansions match and convert only the first character in the expanded value. If pattern is omitted, it is treated like a ‘?’, which matches every character. If parameter is ‘@’ or ‘\*’, the case modification operation is applied to each positional parameter in turn, and the expansion is the resultant list. If parameter is an array variable subscripted with ‘@’ or ‘\*’, the case modification operation is applied to each member of the array in turn, and the expansion is the resultant list.

Do you want me to add a comment indicating this in the script?

**Comment by varGeneric** [comment]
Any update on merging this?

File: send.sh (hunk 1 above)
Comment (lcombs15) [reply send.sh:16]: Sorry for the delay, yeah, could we add link? Just because this is such a true open source effort, we need the documentation.

Something like this?
```suggestion
# More info: https://www.gnu.org/software/bash/manual/bash.html#Shell-Parameter-Expansion
case ${1,,} in
```

Comment (varGeneric) [reply send.sh:16]: Sure, that looks good. Added.

**Review by lcombs15 — APPROVED** [review]

**Comment by lcombs15** [comment]
@k3rn31p4nic has merge access, this looks good to me

**Review by iamtraction — APPROVED** [review]
Thanks for the contribution!
